export const mockAppointments = [
  {
    id: 1,
    date: "2024-01-15",
    time: "09:30 AM",
    medicalHistory: "Hipertensión controlada, alergia a la penicilina.",
    reasonConsultation: "Chequeo anual de salud.",
    userId: 1,
  },
  {
    id: 2,
    date: "2024-02-02",
    time: "02:00 PM",
    medicalHistory: "Asma leve, sin hospitalizaciones previas.",
    reasonConsultation: "Dificultad respiratoria ocasional.",
    userId: 1,
  },
  {
    id: 3,
    date: "2024-03-10",
    time: "11:45 AM",
    medicalHistory: "Diabetes tipo 2, tratamiento con metformina.",
    reasonConsultation: "Revisión de niveles de glucosa.",
    userId: 1,
  },
  {
    id: 4,
    date: "2024-04-05",
    time: "04:15 PM",
    medicalHistory: "Sin antecedentes médicos importantes.",
    reasonConsultation: "Dolor de cabeza persistente.",
    userId: 1,
  },
  {
    id: 5,
    date: "2024-05-20",
    time: "08:00 AM",
    medicalHistory: "Hipotiroidismo, en tratamiento con levotiroxina.",
    reasonConsultation: "Fatiga y aumento de peso reciente.",
    userId: 1,
  },
  {
    id: 6,
    date: "2024-06-18",
    time: "10:30 AM",
    medicalHistory: "Fractura de muñeca hace 3 años, recuperada.",
    reasonConsultation: "Dolor ocasional en la muñeca.",
    userId: 1,
  },
  {
    id: 7,
    date: "2024-07-12",
    time: "01:00 PM",
    medicalHistory: "Alergia al polen, tratamiento con antihistamínicos.",
    reasonConsultation: "Síntomas severos de alergia.",
    userId: 1,
  },
  {
    id: 8,
    date: "2024-08-25",
    time: "03:45 PM",
    medicalHistory: "Cirugía de apendicitis en 2021.",
    reasonConsultation: "Dolor abdominal intermitente.",
    userId: 1,
  },
  {
    id: 9,
    date: "2024-09-30",
    time: "07:15 AM",
    medicalHistory: "Historial de migrañas frecuentes.",
    reasonConsultation: "Evaluación neurológica.",
    userId: 1,
  },
  {
    id: 10,
    date: "2024-10-14",
    time: "05:30 PM",
    medicalHistory: "Sin enfermedades crónicas.",
    reasonConsultation: "Vacunación contra la gripe.",
    userId: 1,
  },
];
